name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "master" ]

jobs:

  publish_image:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t rittik24/marks-predictor:latest
    - name: publish
      run: 
        docker login -u rittik24 -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push rittik24/marks-predictor:latest